alan-eu/activepieces

packages/pieces/community/metabase/.eslintrc.json, packages/pieces/community/metabase/README.md, packages/pieces/community/metabase/package-lock.json, packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/project.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-question.ts, packages/pieces/community/metabase/src/lib/common.ts, packages/pieces/community/metabase/tsconfig.json, packages/pieces/community/metabase/tsconfig.lib.json
Add Metabase piece with action to get results from a "question"
Metabase auth scheme requires a session token (with a fixed duration) that is delivered by a specific endpoint (using email + password)
The Piece will automatically get the token and refresh it when a HTTP 401 error is received, as per Metabase documentation
The token is encrypted (using code which is very similar to `encryption.ts`) and stored at the Project scope
https://www.metabase.com/learn/administration/metabase-api#authenticate-your-requests-with-a-session-token
=> feat: add Metabase piece

packages/server/api/src/app/flows/flow-version/flow-version.service.ts, packages/shared/src/lib/flows/flow-version.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.html, packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.ts
Add the editor's email in a flow's version history
=> feat: display editor in versions history

packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/send-direct-message-action.ts, packages/pieces/community/slack/src/lib/actions/send-message-action.ts, packages/pieces/community/slack/src/lib/actions/upload-file.ts, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/common/utils.ts
- Add standalone "upload file" action which does not share files with a channel
- Add support for arbitrary blocks when sending a message (e.g. to include multiple message attachments at once, etc.)
=> feat: add upload file action and arbitrary blocks support

packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/upsert-document.ts
Allow upserting a document into a Dust data source (so it can be indexed and used by assistants)
=> feat(dust): add action for upserting a document into a database

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/actions/upload-file.ts, packages/pieces/community/slack/src/lib/common/utils.ts
Properly fail when Slack reports an API error (HTTP code may be 200)
This is probably a breaking change for some flows (hence the version change)
=> fix(slack): properly propagate Slack API errors

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/search-messages.ts
Add action to search messages using Slack's query syntax
Pagination is handled
_You will need to re-authenticate your connection to get the extra `search:read` scope_
=> feat(slack): add search message action

packages/server/api/src/app/ee/projects/platform-project-controller.ts, packages/server/api/src/app/ee/projects/platform-project-service.ts, packages/server/api/src/app/ee/projects/platform-user-project-controller.ts
Enable pagination for the list projects endpoint (which currently only returns 50 projects)
=> feat: add pagination support for project list endpoint

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/common.ts
Add support for fragments, i.e. additional context to pass to the assistant
- initial fragment can be passed when creating a new conversation
- new action to add a fragment to an existing conversation
=> feat(dust): add support for fragments

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/add-permission.action.ts, packages/pieces/community/google-drive/src/lib/action/duplicate-file.action.ts, packages/pieces/community/google-drive/src/lib/common/index.ts
Add missing option to support team drives when duplicating a file
=> fix(google-drive): add missing option to support team drives for duplicate file action

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/search-folder-or-file.action.ts
The `google-drive` "search file" action was missing a parameter to use shared drives
Also add create and modify timestamps for each file
=> fix(google-drive): add missing option to search file on shared drives

packages/pieces/community/metabase/src/lib/common.ts
Rename key under which the Metabase session token is stored to make it explicit that it "belongs" to the Metabase piece
=> chore(metabase): rename session token key in store

packages/pieces/community/metabase/src/lib/common.ts
Metabase session token is automatically refreshed when a 401 error is encountered and the original query is automatically retried.
But the retry would use the previous (invalid) token, thus yielding another 401
This PR updates the retry payload to actually use the new token :facepalm:
=> fix(metabase): fix session token refresh

packages/pieces/community/common/src/lib/helpers/index.ts
In some cases the auth mapping for a custom API call needs to be async (e.g. to retrieve a token or cookie dynamically)
=> feat: allow async auth mapping for custom API calls

packages/engine/src/lib/helper/trigger-helper.ts, packages/pieces/community/intercom/package.json, packages/pieces/community/intercom/src/index.ts, packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts, packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
We want to receive a webhook when a conversation note is created
=> feat(intercom): add trigger (webhook) to receive conversation notes

packages/server/api/src/app/user-invitations/user-invitation.module.ts
Fixes case where it's not possible to issue a "PLATFORM" invitation using an API key, as projectId is absent from the payload
=> feat: add exception for /v1/user-invitations as projectId is not mandatory

packages/pieces/community/gmail/package.json, packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
GMail accounts can be configured to send from multiple email addresses - this change allows us to use one of them
=> feat(gmail): allow custom from address

packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/lib/actions/get-question.ts
Metabase only allowed question ids with the form `[0-9]+` but what users instinctively use is often the "full id" of the question `[0-9]+[A-Za-z-]` -> now both are accepted.
=> feat(metabase): allow full question id

packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts, packages/pieces/community/common/src/lib/http/core/http-request.ts, packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-png-rendering.ts, packages/pieces/community/metabase/src/lib/common.ts
Add the `getQuestionPngPreview` action to the Metabase piece.
=> feat: add png rendering action to the Metabase piece

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts
In [this flow](https://automation-staging.alan.com/projects/sLXgp6v5K9RSAHIKP025R/flows/Ok66SEyBmiu2Wfh7RWgIr), I'm trying to get the members of a slack group (@\care_spain_oncall specifically) using a custom API call, but I get the following response from Slack:
```
body:{4 items
ok:false
error:"missing_scope"
needed:"usergroups:read"
provided:"reactions:read,channels:read,channels:manage,channels:history,chat:write,groups:read,groups:write,mpim:read,mpim:write,im:write,users:read,files:write,files:read,users:read.email,reactions:write,chat:write.customize,chat:write.public,groups:history,mpim:history,im:read,im:history"
}
```
In this PR, I've added the necessary permission to allow the API call.
=> feat: add usergroups:read Slack permission

packages/pieces/community/linear/package.json, packages/pieces/community/linear/src/lib/triggers/updated-issue.ts
Make the `team_id` optional for the trigger Linear Issue update to listen to any team for a given automation.
The issue update is triggered with no team selected
=> feat(linear): set team_id optional on linear issue update trigger

packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-dashboard.ts
- Implements a new action that executes all questions in a Metabase dashboard with user-provided parameters and returns their results in a single response.
- The action takes a dashboard ID and parameters object, then returns results indexed by card ID for easy access and further processing.
=> feat: add Metabase get dashboard questions action

packages/pieces/community/rounded-studio/.eslintrc.json, packages/pieces/community/rounded-studio/README.md, packages/pieces/community/rounded-studio/package.json, packages/pieces/community/rounded-studio/project.json, packages/pieces/community/rounded-studio/src/index.ts, packages/pieces/community/rounded-studio/tsconfig.json, packages/pieces/community/rounded-studio/tsconfig.lib.json, tsconfig.base.json
Adds a new activepieces piece for [Rounded Studio](https://rounded.studio/) which allows only for a Custom API Call.
https://github.com/user-attachments/assets/4d45b595-d2c4-4481-ba96-16c00089ec2e
Fixes Q-1278
[Q-1278](https://linear.app/alan-eu/issue/Q-1278/active-pieces-added-roundedstudio-piece-for-custom-api-calls)
=> feat(rounded-studio): add piece with custom api call action

package-lock.json, package.json, packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/helpers/index.ts, packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-graph-question.ts
Add a new action for metabase that allows to get the graph of a question and download it.
This is only a V1 and we might change the way we do that by parsing the HTML later. I'm waiting confirmations to know if this is enough.
There's already an action for that, but the result and method are differents. Let's keep both actions until this one works perfectly.
For that we need an embedding key and that the question is embed (only possible with an admin).
I put the embedding key as a ShortText instead of a SecretText because SecretText are all mandatory (even if the required is false). But by doing this, the field isn't hidden with dots, can be an issue.
Fixes Q-1275
=> feat(metabase): new action get graph

packages/pieces/community/google-docs/package.json, packages/pieces/community/google-docs/src/index.ts, packages/pieces/community/google-docs/src/lib/actions/create-document-based-on-template.action.ts
We allow the user to choose the placeholder he wants for the google doc edit action. It will be "[[]]" by default and he can also choose "{{}}".
Fixes Q-1269
=> feat(google-docs): add placeholder format choice for edit

packages/pieces/community/framework/src/lib/piece.ts, packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/request-action-message.ts, packages/pieces/community/slack/src/lib/actions/send-message-action.ts, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/common/request-action.ts, packages/server/api/src/app/app-event-routing/app-event-routing.module.ts, packages/server/worker/src/lib/utils/machine.ts
We want to receive Slack interaction payloads, e.g. when sending a message with a button we can now cleanly resume the flow (without showing the user an empty tab in their browser)
:warning: the interaction URL must be set to the same event callback URL in the Slack app settings
=> feat(slack): properly handle button interaction payloads
