alan-eu/activepieces

packages/ee/project-members/src/lib/dialogs/invite-project-member-dialog/invite-project-member.component.html

Disable spellcheck / autocorrect on email invite field
Also set type to email

chore: disable spellcheck on email invite field

---

packages/pieces/community/dust/package.json
packages/pieces/community/dust/src/index.ts
packages/pieces/community/dust/src/lib/actions/create-conversation.ts
packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts
packages/pieces/community/dust/src/lib/common.ts

Add action to reply to an existing conversation (possibly using a different agent)

feat(dust): new action to reply to existing conversation

---

packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/lib/actions/send-message-action.ts
packages/pieces/community/slack/src/lib/common/utils.ts

Allow specifying a thread ts to post messages as replies to a thread

feat(slack): allow replies in existing thread

---

packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/index.ts

Upgrade to new Slack OAuth flow: https://api.slack.com/authentication/oauth-v2

feat(slack): upgrade to new OAuth flow

---

packages/server/api/src/app/ee/git-repos/git-repo.module.ts

We want to be able to get a project's git config using an API key

feat: allow retrieving project git config using API token

---

packages/pieces/community/file-helper/package.json
packages/pieces/community/file-helper/src/index.ts
packages/pieces/community/file-helper/src/lib/actions/create-file.ts

Add action to create a file from text content (plain text, CSV, JSON, etc.)

feat(file-helper): add create file from text action

---

packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/index.ts
packages/pieces/community/slack/src/lib/actions/update-message.ts

Add action to update an existing message, e.g. for progress indicators, etc.

feat(slack): add action to update message

---

packages/pieces/community/lever/.eslintrc.json
packages/pieces/community/lever/README.md
packages/pieces/community/lever/package.json
packages/pieces/community/lever/project.json
packages/pieces/community/lever/src/index.ts
packages/pieces/community/lever/src/lib/actions/get-opportunity.ts
packages/pieces/community/lever/src/lib/actions/list-opportunity-forms.ts
packages/pieces/community/lever/src/lib/actions/update-opportunity-stage.ts
packages/pieces/community/lever/tsconfig.json
packages/pieces/community/lever/tsconfig.lib.json

Add Lever integration (using API keys, not OAuth) with custom API call action

feat(lever): add Lever integration

---

packages/pieces/community/google-drive/package.json
packages/pieces/community/google-drive/src/lib/common/index.ts
packages/pieces/community/google-drive/src/lib/triggers/new-file.ts

fix(google-drive): new file trigger now supports shared drives

---

packages/pieces/community/google-drive/package.json
packages/pieces/community/google-drive/src/lib/action/upload-file.ts

fix(google-drive): support shared drives when uploading a file

---

packages/pieces/community/google-sheets/package.json
packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts

fix(google-sheets): fix missing option for trigger

---

packages/pieces/community/slack/src/lib/actions/upload-file.ts

feat(slack): add optional filename param when uploading a file

---

packages/pieces/community/google-sheets/package.json
packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts

fix(google-sheets): fix missing option for other trigger

---

packages/pieces/community/linear/package.json
packages/pieces/community/linear/src/lib/actions/comments/create-comment.ts
packages/pieces/community/linear/src/lib/actions/issues/create-issue.ts
packages/pieces/community/linear/src/lib/actions/issues/update-issue.ts
packages/pieces/community/linear/src/lib/actions/projects/create-project.ts
packages/pieces/community/linear/src/lib/actions/projects/update-project.ts

feat(linear): enrich actions output

---

packages/pieces/community/lever/package.json
packages/pieces/community/lever/src/lib/actions/add-feedback-to-opportunity.ts

Allow posting feedback even when no interview has been scheduled, using any template available

feat(lever): allow adding arbitrary feedback using any template available

---

packages/pieces/community/metabase/package.json
packages/pieces/community/metabase/src/index.ts
packages/pieces/community/metabase/src/lib/actions/get-question.ts
packages/pieces/community/metabase/src/lib/common.ts

Metabase 0.49 introduced a new API key auth mechanism which is simpler and safer to use
https://www.metabase.com/releases/metabase-49#authenticate-api-requests-with-api-keys

feat(metabase): switch to new API key auth mechanism

---

packages/pieces/community/google-drive/package.json
packages/pieces/community/google-drive/src/lib/action/create-new-folder.ts
packages/pieces/community/google-drive/src/lib/action/create-new-text-file.ts

feat(google-drive): add support for team drives when creating directories and files

---

packages/pieces/community/linear/package.json
packages/pieces/community/linear/src/index.ts
packages/pieces/community/linear/src/lib/actions/raw-graphql-query.ts
packages/pieces/community/linear/src/lib/common/client.ts

feat(linear): add action to perform a raw GraphQL query

---

packages/pieces/community/google-drive/package.json
packages/pieces/community/google-drive/src/lib/action/save-file-as-pdf.action.ts
packages/pieces/community/google-drive/src/lib/action/upload-file.ts

feat(google-drive): add support for all drives to pdf export action

---

packages/pieces/community/lever/package.json
packages/pieces/community/lever/src/lib/common.ts

feat(lever): improve add-feedback action

---

packages/pieces/community/photoroom/.eslintrc.json
packages/pieces/community/photoroom/README.md
packages/pieces/community/photoroom/package.json
packages/pieces/community/photoroom/project.json
packages/pieces/community/photoroom/src/index.ts
packages/pieces/community/photoroom/src/lib/actions/remove-background.ts
packages/pieces/community/photoroom/tsconfig.json
packages/pieces/community/photoroom/tsconfig.lib.json
tsconfig.base.json

Add photoroom integration with action to remove an image's background

feat(photoroom): add action to remove the background of an arbitrary image

---

packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/index.ts
packages/pieces/community/slack/src/lib/actions/get-channel-history.ts

feat(slack): add conversation.history action

---

packages/pieces/community/linear/package.json
packages/pieces/community/linear/src/lib/actions/issues/create-issue.ts

Description was not passed to Linear when creating an issue

feat(linear): fix missing description when creating an issue

---

packages/pieces/community/datocms/.eslintrc.json
packages/pieces/community/datocms/README.md
packages/pieces/community/datocms/package.json
packages/pieces/community/datocms/project.json
packages/pieces/community/datocms/src/index.ts
packages/pieces/community/datocms/tsconfig.json
packages/pieces/community/datocms/tsconfig.lib.json
tsconfig.base.json

Add piece for DatoCMS: https://www.datocms.com/
API docs: https://www.datocms.com/docs/content-management-api
Closes Q-713

feat(datocms): add piece with custom api call action

---

packages/pieces/community/captain-data/.eslintrc.json
packages/pieces/community/captain-data/README.md
packages/pieces/community/captain-data/package.json
packages/pieces/community/captain-data/project.json
packages/pieces/community/captain-data/src/index.ts
packages/pieces/community/captain-data/src/lib/actions/get-job-results.ts
packages/pieces/community/captain-data/src/lib/actions/launch-workflow.ts
packages/pieces/community/captain-data/src/lib/common.ts
packages/pieces/community/captain-data/tsconfig.json
packages/pieces/community/captain-data/tsconfig.lib.json
tsconfig.base.json

feat(captain-data): add piece with actions to schedule a workflow and retrieve results

---

package-lock.json
package.json
packages/pieces/community/intercom/package.json
packages/pieces/community/intercom/src/index.ts
packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts

Add optional keyword to trigger hooks only when a specific keyword is included in a note

feat(intercom): add optional keyword to filter incoming note hooks

---

packages/pieces/community/text-helper/.eslintrc.json
packages/pieces/community/text-helper/package.json
packages/pieces/community/text-helper/src/index.ts
packages/pieces/community/text-helper/src/lib/actions/find.ts
packages/pieces/community/text-helper/src/lib/actions/replace.ts
packages/pieces/community/text-helper/src/lib/actions/split.ts
packages/pieces/community/text-helper/src/lib/actions/strip-html.ts

Add action to strip HTML tags from a string

feat(text-helper): add action to strip html tags

---

package-lock.json
package.json
packages/pieces/community/intercom/package.json
packages/pieces/community/intercom/src/index.ts
packages/pieces/community/intercom/src/lib/actions/add-note-to-conversation.ts
packages/pieces/community/intercom/src/lib/actions/create-contact.action.ts
packages/pieces/community/intercom/src/lib/actions/create-or-get-contact.action.ts
packages/pieces/community/intercom/src/lib/actions/reply-to-conversation.ts
packages/pieces/community/intercom/src/lib/actions/send-message.action.ts
packages/pieces/community/intercom/src/lib/common/index.ts
packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts

- Switch to official SDK
- Add support for Europe and Australia regions (different URLs)
- Add actions to reply / add a note to an existing conversation

feat(intercom): add support for EU and AU regions, add new actions

---

packages/pieces/community/todoist/package.json
packages/pieces/community/todoist/src/lib/actions/create-task-action.ts
packages/pieces/community/todoist/src/lib/actions/update-task.action.ts
packages/pieces/community/todoist/src/lib/common/client/rest-client.ts
packages/pieces/community/todoist/src/lib/common/models.ts

Todoist API supports natural language due dates (e.g. Tomorrow, this Monday, etc.)

feat(todoist): add support for natural language due dates

---

packages/pieces/community/intercom/package.json
packages/pieces/community/intercom/src/index.ts
packages/pieces/community/intercom/src/lib/triggers/conversation-assigned.ts
packages/pieces/community/intercom/src/lib/triggers/conversation-closed.ts
packages/pieces/community/intercom/src/lib/triggers/conversation-snoozed.ts
packages/pieces/community/intercom/src/lib/triggers/conversation-unsnoozed.ts
packages/pieces/community/intercom/src/lib/triggers/new-conversation-from-user.ts
packages/pieces/community/intercom/src/lib/triggers/reply-from-admin.ts
packages/pieces/community/intercom/src/lib/triggers/reply-from-user.ts

feat(intercom): add various conversation triggers

---

packages/pieces/community/gmail/.eslintrc.json
packages/pieces/community/gmail/package.json
packages/pieces/community/gmail/src/index.ts
packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
packages/pieces/community/gmail/src/lib/common/props.ts
packages/pieces/community/gmail/src/lib/triggers/new-email.ts

feat(gmail): add option to reply to thread and draft messages

---

package-lock.json
package.json
packages/pieces/community/notion/package.json
packages/pieces/community/notion/src/lib/actions/get-page-or-block-children.ts

feat(notion): add option to export page content to markdown

---

packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/index.ts
packages/pieces/community/slack/src/lib/actions/find-user-by-handle.ts
packages/pieces/community/slack/src/lib/actions/set-user-status.ts
packages/pieces/community/slack/src/lib/common/props.ts
packages/pieces/community/slack/src/lib/triggers/new-message.ts

Closes Q-760
Closes Q-762
Closes Q-763

feat(slack): add new actions

---

packages/pieces/community/linear/package.json
packages/pieces/community/linear/src/lib/common/props.ts

feat(linear): fix pagination bug

---

packages/pieces/community/dust/package.json
packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts
packages/pieces/community/dust/src/lib/actions/create-conversation.ts

feat(dust): add mime type after breaking API change

---

packages/pieces/community/dust/package.json
packages/pieces/community/dust/src/index.ts
packages/pieces/community/dust/src/lib/actions/get-conversation.ts
packages/pieces/community/dust/src/lib/common.ts

feat(dust): improve error management and add action to get existing conversation

---

package-lock.json
package.json
packages/pieces/community/github/package.json
packages/pieces/community/github/src/index.ts
packages/pieces/community/github/src/lib/actions/raw-graphql-query.ts

feat(github): add octokit sdk and raw graphql action

---

packages/pieces/community/intercom/package.json
packages/pieces/community/intercom/src/index.ts
packages/pieces/community/intercom/src/lib/triggers/conversation-rated.ts

feat(intercom): add conversation.rated trigger

---

packages/pieces/community/dust/package.json
packages/pieces/community/dust/src/lib/actions/create-conversation.ts
packages/pieces/community/dust/src/lib/common.ts

feat(dust): allow creation of empty conversations

---

packages/pieces/community/github/package.json
packages/pieces/community/github/src/lib/trigger/index.ts

feat(github): add trigger on new push

---

package-lock.json
package.json
packages/pieces/community/text-helper/package.json
packages/pieces/community/text-helper/src/index.ts
packages/pieces/community/text-helper/src/lib/actions/slugify.ts

feat(text-helper): add slugify action

---

packages/pieces/community/activepieces/package.json
packages/pieces/community/activepieces/src/index.ts
packages/pieces/community/activepieces/src/lib/actions/create-project-member.ts
packages/pieces/community/activepieces/src/lib/actions/create-project.ts
packages/pieces/community/activepieces/src/lib/actions/delete-project-member.ts
packages/pieces/community/activepieces/src/lib/actions/list-project-member.ts
packages/pieces/community/activepieces/src/lib/actions/list-project.ts
packages/pieces/community/activepieces/src/lib/actions/update-project.ts

feat(activepieces): add customizable base URL to use on self-hosted platforms

---

packages/pieces/community/customer-io/package.json
packages/pieces/community/customer-io/src/index.ts
packages/pieces/community/customer-io/src/lib/actions/create_event.ts
packages/pieces/community/customer-io/src/lib/common/index.ts

feat(customer-io): add support for EU workspaces

---

package-lock.json
package.json
packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/index.ts
packages/pieces/community/slack/src/lib/actions/markdown-to-slack-format.ts

feat(slack): add action to convert markdown text to Slack custom format

---

packages/pieces/community/google-drive/package.json
packages/pieces/community/google-drive/src/lib/action/move-file.ts

feat(google-drive): add option to support all drives when moving a file

---

packages/pieces/community/google-drive/package.json
packages/pieces/community/google-drive/src/lib/action/move-file.ts

fix(google-drive): files could not be moved

---

packages/pieces/community/salesforce/package.json
packages/pieces/community/salesforce/src/index.ts

feat(salesforce): add custom API call action

---

packages/pieces/community/scenario/.eslintrc.json
packages/pieces/community/scenario/README.md
packages/pieces/community/scenario/package.json
packages/pieces/community/scenario/project.json
packages/pieces/community/scenario/src/index.ts
packages/pieces/community/scenario/tsconfig.json
packages/pieces/community/scenario/tsconfig.lib.json
tsconfig.base.json

feat(scenario): add Scenario piece with custom api call action

---

packages/pieces/community/bamboohr/.eslintrc.json
packages/pieces/community/bamboohr/README.md
packages/pieces/community/bamboohr/package.json
packages/pieces/community/bamboohr/project.json
packages/pieces/community/bamboohr/src/index.ts
packages/pieces/community/bamboohr/tsconfig.json
packages/pieces/community/bamboohr/tsconfig.lib.json
tsconfig.base.json

feat(bamboohr): add BambooHR piece with custom api call action

---

packages/pieces/community/ashby/.eslintrc.json
packages/pieces/community/ashby/README.md
packages/pieces/community/ashby/package.json
packages/pieces/community/ashby/project.json
packages/pieces/community/ashby/src/index.ts
packages/pieces/community/ashby/tsconfig.json
packages/pieces/community/ashby/tsconfig.lib.json
tsconfig.base.json

feat(ashby): add basic Ashby piece

---

packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/lib/common/request-action.ts

fix(slack): fix request action

---

packages/pieces/community/common/package.json
packages/pieces/community/common/src/lib/helpers/index.ts
packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/index.ts

feat: add optional extra props for custom API call

---

packages/pieces/community/intercom/package.json
packages/pieces/community/intercom/src/index.ts
packages/pieces/community/intercom/src/lib/triggers/conversation-part-tagged.ts

feat(intercom): add trigger for tagged conversations

---

packages/pieces/community/customer-io/package.json
packages/pieces/community/customer-io/src/lib/actions/create_event.ts

fix(customerio): don't send customer identifier as event id

---

packages/pieces/community/dust/package.json
packages/pieces/community/dust/src/lib/common.ts

fix(dust): update Dust error format after API change

---

packages/server/api/src/app/webhooks/webhook-controller.ts
packages/shared/src/lib/engine/engine-operation.ts

feat: add rawBody to webhook trigger payload

---

packages/pieces/community/google-slides/package.json
packages/pieces/community/google-slides/src/index.ts
packages/pieces/community/google-slides/src/lib/actions/generate-from-template.ts
packages/pieces/community/google-slides/src/lib/actions/get-presentation.ts
packages/pieces/community/google-slides/src/lib/actions/refresh-charts.ts
packages/pieces/community/google-slides/src/lib/commons/common.ts

Create new actions for GSlide: get, generated from template and refresh charts.
Fixes Q-1118

feat: New actions for GSlide

---

packages/pieces/community/intercom/src/lib/triggers/conversation-part-tagged.ts

fix(intercom): remove wrong test data for trigger

---

packages/pieces/community/rss/package.json
packages/pieces/community/rss/src/index.ts
packages/pieces/community/rss/src/lib/common/getId.ts
packages/pieces/community/rss/src/lib/common/props.ts
packages/pieces/community/rss/src/lib/common/sampleData.ts
packages/pieces/community/rss/src/lib/triggers/new-item-list-triggers.ts
packages/pieces/community/rss/src/lib/triggers/new-item-trigger.ts

We created a new trigger that allow a list instead of a single link feed for rss

feat: create new trigger list feed for rss

---

packages/pieces/community/dust/package.json
packages/pieces/community/dust/src/index.ts
packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts
packages/pieces/community/dust/src/lib/actions/create-conversation.ts
packages/pieces/community/dust/src/lib/actions/get-conversation.ts
packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts
packages/pieces/community/dust/src/lib/actions/upsert-document.ts
packages/pieces/community/dust/src/lib/common.ts

feat(dust): add support for EU region

---

packages/pieces/community/dust/src/index.ts
packages/pieces/community/intercom/package.json

feat(dust): add custom api call action

---

package-lock.json
package.json
packages/pieces/community/dust/package.json

feat(dust): bump dust SDK version to re-allow creating conversation with empty messages

---

packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/index.ts

feat(slack): add links:* scope

---

packages/pieces/community/docusign/package.json
packages/pieces/community/docusign/src/index.ts

feat(docusign): remove extra 'api/' from consent URL

---

packages/pieces/community/docusign/package.json
packages/pieces/community/docusign/src/lib/actions/get-document.ts

fix(docusign): fix filename which was always archive.zip even for PDFs

---

packages/pieces/community/notion/package.json
packages/pieces/community/notion/src/lib/common/index.ts

feat(notion): improve error management when generating dynamic input properties

---

packages/pieces/community/slack/package.json
packages/pieces/community/slack/src/index.ts
packages/pieces/community/slack/src/lib/actions/list-users.ts

feat(slack): add action to list all users of a workspace
